[package]
name = "loops"
version = "0.1.0"
authors = ["Tuyen Dang <3666422+tuyendq@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
